
import java.awt.BorderLayout;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.FlowLayout;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 2damb
 */
public class Actividad_9_2 extends javax.swing.JFrame {

    /**
     * Creates new form Actividad_9_2
     */
    public Actividad_9_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoBottonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        profesionLabel = new javax.swing.JLabel();
        introduceProfesionText = new javax.swing.JTextField();
        numeroDeHermanosLabel = new javax.swing.JLabel();
        hermanosSpinner = new javax.swing.JSpinner();
        edadLabel = new javax.swing.JLabel();
        edadComboBox = new javax.swing.JComboBox<>();
        sexoLabel = new javax.swing.JLabel();
        hombreRadioButton = new javax.swing.JRadioButton();
        mujerRadioButton = new javax.swing.JRadioButton();
        noBinarioRadioButton = new javax.swing.JRadioButton();
        practicasDeportesCheckBox = new javax.swing.JCheckBox();
        cualLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeportesList = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        fraseLabel = new javax.swing.JLabel();
        comprasSlider = new javax.swing.JSlider();
        comprasLabel = new javax.swing.JLabel();
        vetTelevisionLabel = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        irAlCineLabel = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        restablecerButton = new javax.swing.JButton();

        sexoBottonGroup.add(hombreRadioButton);
        sexoBottonGroup.add(mujerRadioButton);
        sexoBottonGroup.add(noBinarioRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad_9_2");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(720, 480));

        profesionLabel.setText("Profesión:");

        introduceProfesionText.setText("Técnico Superior en Desarrollo de Aplicaciones Multiplataforma");
        introduceProfesionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introduceProfesionTextActionPerformed(evt);
            }
        });

        numeroDeHermanosLabel.setText("Número de hermanos");

        edadLabel.setText("Edad:");

        edadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entre 10 y 30", "Entre 30 y 40", "Entre 40 y 50", "Más de 60" }));

        sexoLabel.setText("Sexo");

        hombreRadioButton.setText("Hombre");

        mujerRadioButton.setText("Mujer");
        mujerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mujerRadioButtonActionPerformed(evt);
            }
        });

        noBinarioRadioButton.setText("No binario");
        noBinarioRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBinarioRadioButtonActionPerformed(evt);
            }
        });

        practicasDeportesCheckBox.setText("¿Practicas alguon deporte?");
        practicasDeportesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practicasDeportesCheckBoxActionPerformed(evt);
            }
        });

        cualLabel.setText("¿Cual?");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        listaDeportesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fútbol", "Baloncesto", "Tenis", "Volleyball", "Pádel" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaDeportesList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        fraseLabel.setText("Márque del 1 al 10 su grado de afición a:");

        comprasLabel.setText("Compras:");

        vetTelevisionLabel.setText("Ver Televisión:");

        irAlCineLabel.setText("Ir al cine:");

        aceptarButton.setText("ACEPTAR");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("CANCELAR");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        restablecerButton.setText("RESTABLECER");
        restablecerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restablecerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(irAlCineLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(vetTelevisionLabel))
                            .addComponent(fraseLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(comprasLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hombreRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(mujerRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(noBinarioRadioButton))
                                    .addComponent(sexoLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(profesionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(introduceProfesionText))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(practicasDeportesCheckBox)
                                                .addGap(83, 83, 83))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(numeroDeHermanosLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(hermanosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(edadLabel)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cualLabel)
                                            .addComponent(edadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSlider2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                                .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comprasSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(restablecerButton)
                        .addGap(92, 92, 92)
                        .addComponent(cancelarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptarButton)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesionLabel)
                    .addComponent(introduceProfesionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDeHermanosLabel)
                    .addComponent(hermanosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadLabel)
                    .addComponent(edadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sexoLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hombreRadioButton)
                    .addComponent(mujerRadioButton)
                    .addComponent(noBinarioRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(practicasDeportesCheckBox)
                    .addComponent(cualLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fraseLabel)
                .addGap(29, 29, 29)
                .addComponent(comprasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprasSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vetTelevisionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(irAlCineLabel)
                .addGap(18, 18, 18)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton)
                    .addComponent(cancelarButton)
                    .addComponent(restablecerButton))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introduceProfesionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introduceProfesionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introduceProfesionTextActionPerformed

    private void mujerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mujerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mujerRadioButtonActionPerformed

    private void noBinarioRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBinarioRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noBinarioRadioButtonActionPerformed

    private void practicasDeportesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practicasDeportesCheckBoxActionPerformed
        
        
    }//GEN-LAST:event_practicasDeportesCheckBoxActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        
        JDialog dialogo = new JDialog(this,"ATENCIÓN",true);
        dialogo.setSize(300,150);
        dialogo.setLayout(new BorderLayout());
        
        JLabel label = new JLabel("¿Estas seguro de enviar estos datos?");
        label.setHorizontalAlignment(JLabel.CENTER);
        dialogo.add(label, BorderLayout.CENTER);
        
        JButton botonCancelar = new JButton("Cancelar");
        botonCancelar.addActionListener((e) -> {
           
            dialogo.dispose();
            
        });
        
        JButton botonEnviar = new JButton("Enviar");
        botonEnviar.addActionListener((e) -> {
            
            String [] dep = {"Fútbol","Baloncesto","Tenis","Volleyball","Pádel"};
            dialogo.dispose();
            edadComboBox.setSelectedIndex(0);
            introduceProfesionText.setText("");
            comprasSlider.setValue(50);
            jSlider1.setValue(50);
            jSlider2.setValue(50);
            practicasDeportesCheckBox.setSelected(false);
            sexoBottonGroup.clearSelection();
            listaDeportesList.setListData(dep);
            hermanosSpinner.setValue(0);
            
        });
        
        JPanel panelBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        panelBotones.add(botonCancelar);
        panelBotones.add(botonEnviar);
        
        dialogo.add(panelBotones,BorderLayout.SOUTH);
        
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
        
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void restablecerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restablecerButtonActionPerformed
        
            String [] dep = {"Fútbol","Baloncesto","Tenis","Volleyball","Pádel"};
            edadComboBox.setSelectedIndex(0);
            introduceProfesionText.setText("");
            comprasSlider.setValue(50);
            jSlider1.setValue(50);
            jSlider2.setValue(50);
            practicasDeportesCheckBox.setSelected(false);
            sexoBottonGroup.clearSelection();
            listaDeportesList.setListData(dep);
            hermanosSpinner.setValue(0);

    }//GEN-LAST:event_restablecerButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad_9_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad_9_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad_9_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad_9_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_9_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel comprasLabel;
    private javax.swing.JSlider comprasSlider;
    private javax.swing.JLabel cualLabel;
    private javax.swing.JComboBox<String> edadComboBox;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JLabel fraseLabel;
    private javax.swing.JSpinner hermanosSpinner;
    private javax.swing.JRadioButton hombreRadioButton;
    private javax.swing.JTextField introduceProfesionText;
    private javax.swing.JLabel irAlCineLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JList<String> listaDeportesList;
    private javax.swing.JRadioButton mujerRadioButton;
    private javax.swing.JRadioButton noBinarioRadioButton;
    private javax.swing.JLabel numeroDeHermanosLabel;
    private javax.swing.JCheckBox practicasDeportesCheckBox;
    private javax.swing.JLabel profesionLabel;
    private javax.swing.JButton restablecerButton;
    private javax.swing.ButtonGroup sexoBottonGroup;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JLabel vetTelevisionLabel;
    // End of variables declaration//GEN-END:variables
}
